### ISSUE TITLE
"Level Select" level selection menu leads back to campaign selection...

### ISSUE THREAD

**Issue by sauer2** [cxong/cdogs-sdl#508] opened 2017-07-10 15:54 UTC
... instead to the level briefing screen.

**Comment by cxong** [comment] 2017-07-11 12:11
This should be fixed already

**Comment by sauer2** [comment] 2017-07-11 12:24
It's still there, though.

Steps to reproduce:

1. Select level of a campaign (works the first time)
2. Exit the game (or lose the game)
3. Try again to select a level -> you get to the campaign menu

**Comment by cxong** [comment] 2017-07-11 13:17
I can't reproduce it:

- Start Harmful Crysalis, level 2
- Quit game immediately after starting game
- Go back into Harmful Crysalis, level 2
- Campaign loaded, starting from Game Options screen

**Comment by sauer2** [comment] 2017-07-11 13:25
@cxong Apparently it only happens if you lose the first game. My mistake.

**Comment by cxong** [comment] 2017-07-11 13:47
thanks, found the problem now 👍

**Closed** 2017-07-11 13:47 UTC

**Comment by sauer2** [comment] 2017-07-11 13:53
No problem ;)
