### ISSUE TITLE
Changing weapons while standing still

### ISSUE THREAD

**Issue by PavanLuca** [cxong/cdogs-sdl#810] opened 2023-07-22 18:45 UTC
Changing weapons while not moving is something I never really enjoyed much so far, I often dash instead of changing weapon for this, sometimes even lose. Imagine stopping in the middle of shootouts just to change weapon 😒. Please allow changing them at any moment, or disallow it only when shooting.

**Comment by cxong** [comment] 2023-07-27 13:33
Duplicate of #611

**Closed by cxong** 2023-07-27 13:33 UTC
